### ISSUE TITLE
feat(prime numbers): add code for Miller–Rabin deterministic and non deterministic primality test

### ISSUE THREAD

**Issue by Ansh-Sarkar** [ccgcv/Cplus-plus-for-hacktoberfest#115]
## Proposal

Add code for the extremely fast primality testing of numbers using the Miller–Rabin algorithm. I will be implementing both the following types of algorithms and possible variations if any

- [ ] Deterministic
- [ ] Non Deterministic

Would love to work on this issue. Kindly do consider assigning it to me if you think this would be a worthwhile contribution to the repository.

**Comment by ccgcv** [comment]
Sure, go ahead @Ansh-Sarkar
