### ISSUE TITLE
DSU implementation in C++

### ISSUE THREAD

**Issue by debapriya36** [ccgcv/Cplus-plus-for-hacktoberfest#92]
Hi @ccgcv , i want to add disjoint set union implementation in c++.
can you plz assign it to me ?

**Comment by abhayanand08** [comment]
@ccgcv I want to add solution of this issue. Can you kindly assign this issue to me .

**Comment by ccgcv** [comment]
I guess tries and more algorithmic solution of graphs will be appreciated @debapriya36 and @abhayanand08

**Comment by abhayanand08** [comment]
ok @ccgcv i will be add those only

**Comment by abhayanand08** [comment]
@ccgcv I have added Disjoint Set Union Implementation. Kindly check my PR
